global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - "alerts-payments.yml"
  - "alerts-rate-limit.yml"
  - "alerts-http-db-bots.yml"

scrape_configs:
  - job_name: 'faceit-api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics'

  - job_name: 'faceit-web'
    static_configs:
      - targets: ['web:3000']
    metrics_path: '/api/metrics'

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'postgres'
    static_configs:
      - targets: ['db:5432']

  - job_name: 'discord-bot'
    static_configs:
      - targets: ['discord_bot:9101']

  - job_name: 'telegram-bot'
    static_configs:
      - targets: ['telegram_bot:9102']
