apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: faceit-postgres
  namespace: faceit-prod
$patch: delete
---
apiVersion: v1
kind: Service
metadata:
  name: faceit-postgres
  namespace: faceit-prod
$patch: delete
