apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yml
- configmap.yml
- secret.yml
- deployment-ollama.yml
- statefulset-postgres.yml
- deployment-redis.yml
- deployment-api.yml
- deployment-celery-worker.yml
- deployment-celery-beat.yml
- deployment-web.yml
- ingress.yml
- uploads-nginx-configmap.yml
- uploads-nginx-deployment.yml
- uploads-ingress.yml

commonLabels:
  environment: production

images:
- name: registry.pattmsc.online/faceit-api
  newTag: v0.4.0
- name: registry.pattmsc.online/faceit-web
  newTag: v0.4.0
