apiVersion: v1
kind: Secret
metadata:
  name: faceit-secrets
type: Opaque
data:
  # Кодируй в base64 свои настоящие значения!
  SECRET_KEY: "your-secret-key-base64"
  FACEIT_API_KEY: "your-faceit-api-key-base64"  
  FACEIT_CLIENT_ID: "your-faceit-client-id-base64"
  FACEIT_CLIENT_SECRET: "your-faceit-client-secret-base64"
  GROQ_API_KEY: "your-groq-api-key-base64"
  DB_PASSWORD: "your-db-password-base64"
  REDIS_PASSWORD: "your-redis-password-base64"
  GF_PASSWORD: "your-grafana-password-base64"
  YOOKASSA_SHOP_ID: "your-yookassa-shop-id-base64"
  YOOKASSA_SECRET_KEY: "your-yookassa-secret-key-base64"
